version: '3'
services:
  selenium_hub:
    image: selenium/hub:4.32
    ports:
      - 4444:4444
      - 4443:4443
      - 4442:4442
  chrome-node:
    image: selenium/node-chromium:4.32
    shm_size: 2g 
    deploy:
      replicas: 3
    depends_on: 
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox-node:
    image: selenium/node-firefox:4.32
    shm_size: 2g 
    deploy:
      replicas: 3
    depends_on:
      - selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=selenium_hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443 