services:
  selenium-hub:
    image: selenium/hub:4.32
    ports:
      - 4444:4444
  chrome-node:
    image: selenium/node-chromium:4.32
    shm_size: 2gb
    deploy:
      replicas: 1
    depends_on:
      - selenium-hub
    environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443  
    - SE_NODE_MAX_SESSIONS=1
    - SE_VNC_NO_PASSWORD=1
  # firefox-node:
  #   image: selenium/node-firefox:4.32
  #   shm_size: 2gb
  #   deploy:
  #     replicas: 1
  #   depends_on:
  #     - selenium-hub  
  #   environment:
  #   - SE_EVENT_BUS_HOST=selenium-hub
  #   - SE_EVENT_BUS_PUBLISH_PORT=4442
  #   - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  #   - SE_NODE_MAX_SESSIONS=1
  #   - SE_VNC_NO_PASSWORD=1  
  docker-selenium:
    image: pronoydas/automation-selenium-docker
    depends_on:
     - selenium-hub
     - chrome-node    
    environment:
    - HUB_HOST=selenium-hub
    - IS_ENABLE=true
    - BROWSER=chrome
    - HOST_IP=192.168.1.38
    - TEST_SUITE=test-suite.xml
    - THREAD_COUNT=1 
    volumes:
     -  /C:/Users/prono/OneDrive/Documents/AutomationWIthDockerAndCICD/Result:/home/docker-selenium/test-output